// flow-typed signature: a6100ef8b60f2fbb3caa418610894679
// flow-typed version: <<STUB>>/ansi-to-html_v^0.4.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-to-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-to-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ansi-to-html/gruntFile' {
  declare module.exports: any;
}

declare module 'ansi-to-html/lib/ansi_to_html' {
  declare module.exports: any;
}

declare module 'ansi-to-html/lib/cli' {
  declare module.exports: any;
}

declare module 'ansi-to-html/test/ansi_to_html' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ansi-to-html/gruntFile.js' {
  declare module.exports: $Exports<'ansi-to-html/gruntFile'>;
}
declare module 'ansi-to-html/lib/ansi_to_html.js' {
  declare module.exports: $Exports<'ansi-to-html/lib/ansi_to_html'>;
}
declare module 'ansi-to-html/lib/cli.js' {
  declare module.exports: $Exports<'ansi-to-html/lib/cli'>;
}
declare module 'ansi-to-html/test/ansi_to_html.js' {
  declare module.exports: $Exports<'ansi-to-html/test/ansi_to_html'>;
}
