// flow-typed signature: 1af1c28a903b51448fe5b00d828cb10d
// flow-typed version: <<STUB>>/ansi-to-html_v^0.6.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-to-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-to-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ansi-to-html/lib/ansi_to_html' {
  declare module.exports: any;
}

declare module 'ansi-to-html/lib/cli' {
  declare module.exports: any;
}

declare module 'ansi-to-html/test/ansi_to_html' {
  declare module.exports: any;
}

declare module 'ansi-to-html/test/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ansi-to-html/lib/ansi_to_html.js' {
  declare module.exports: $Exports<'ansi-to-html/lib/ansi_to_html'>;
}
declare module 'ansi-to-html/lib/cli.js' {
  declare module.exports: $Exports<'ansi-to-html/lib/cli'>;
}
declare module 'ansi-to-html/test/ansi_to_html.js' {
  declare module.exports: $Exports<'ansi-to-html/test/ansi_to_html'>;
}
declare module 'ansi-to-html/test/cli.js' {
  declare module.exports: $Exports<'ansi-to-html/test/cli'>;
}
