// flow-typed signature: 79b71ce8fe8304a0e134d2016a381556
// flow-typed version: <<STUB>>/babel-plugin-react-for-atom_vgithub:alanzanattadev/babel-plugin-react-for-atom/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-for-atom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-for-atom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-react-for-atom/index' {
  declare module.exports: $Exports<'babel-plugin-react-for-atom'>;
}
declare module 'babel-plugin-react-for-atom/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-for-atom'>;
}
