// flow-typed signature: 94777fb46cb1b93a127535a0688aac80
// flow-typed version: <<STUB>>/chrome-remote-interface_v^0.24.2/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrome-remote-interface'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrome-remote-interface' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chrome-remote-interface/bin/client' {
  declare module.exports: any;
}

declare module 'chrome-remote-interface/chrome-remote-interface' {
  declare module.exports: any;
}

declare module 'chrome-remote-interface/lib/api' {
  declare module.exports: any;
}

declare module 'chrome-remote-interface/lib/chrome' {
  declare module.exports: any;
}

declare module 'chrome-remote-interface/lib/defaults' {
  declare module.exports: any;
}

declare module 'chrome-remote-interface/lib/devtools' {
  declare module.exports: any;
}

declare module 'chrome-remote-interface/lib/external-request' {
  declare module.exports: any;
}

declare module 'chrome-remote-interface/lib/websocket-wrapper' {
  declare module.exports: any;
}

declare module 'chrome-remote-interface/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chrome-remote-interface/bin/client.js' {
  declare module.exports: $Exports<'chrome-remote-interface/bin/client'>;
}
declare module 'chrome-remote-interface/chrome-remote-interface.js' {
  declare module.exports: $Exports<'chrome-remote-interface/chrome-remote-interface'>;
}
declare module 'chrome-remote-interface/index' {
  declare module.exports: $Exports<'chrome-remote-interface'>;
}
declare module 'chrome-remote-interface/index.js' {
  declare module.exports: $Exports<'chrome-remote-interface'>;
}
declare module 'chrome-remote-interface/lib/api.js' {
  declare module.exports: $Exports<'chrome-remote-interface/lib/api'>;
}
declare module 'chrome-remote-interface/lib/chrome.js' {
  declare module.exports: $Exports<'chrome-remote-interface/lib/chrome'>;
}
declare module 'chrome-remote-interface/lib/defaults.js' {
  declare module.exports: $Exports<'chrome-remote-interface/lib/defaults'>;
}
declare module 'chrome-remote-interface/lib/devtools.js' {
  declare module.exports: $Exports<'chrome-remote-interface/lib/devtools'>;
}
declare module 'chrome-remote-interface/lib/external-request.js' {
  declare module.exports: $Exports<'chrome-remote-interface/lib/external-request'>;
}
declare module 'chrome-remote-interface/lib/websocket-wrapper.js' {
  declare module.exports: $Exports<'chrome-remote-interface/lib/websocket-wrapper'>;
}
declare module 'chrome-remote-interface/webpack.config.js' {
  declare module.exports: $Exports<'chrome-remote-interface/webpack.config'>;
}
