// flow-typed signature: 53d39658de881a2d2175ae4f99b9047f
// flow-typed version: <<STUB>>/flow-language-server_v^0.2.5/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-language-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-language-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-language-server/dirs' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/__tests__/ConnectionMock' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/__tests__/TextDocuments.test' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/bin/cli' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/Completion' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/Definition' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/Diagnostics' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/flow-versions/__tests__/flowBinForRoot.test' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/flow-versions/constants' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/flow-versions/flowBinForRoot' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/flow-versions/githubSemverDownloader' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/flow-versions/types' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/flow-versions/utils' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/Hover' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/index' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/logging/connectionConsoleAppender' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/logging/fileAppender' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/logging/initializeLogging' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-analytics' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-debugger-interfaces/rpc-types' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-common/lib/main' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/astToOutline' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/config' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/diagnosticsParser' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowConstants' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowExecInfoContainer' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowHelpers' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowIDEConnection' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowIDEConnectionWatcher' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/flowOutputTypes' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowProcess' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowService' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowServiceState' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowSingleProjectLanguageService' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowVersion' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/prettyPrintTypes' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/HostServicesAggregator' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/main' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/MultiProjectLanguageService' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/NullLanguageService' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/rpc-types' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/ServerLanguageService' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-language-service/lib/LanguageService' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/ConfigObserver' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/constants' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/FileCache' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/FileVersionNotifier' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/main' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/OpenFilesService' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/rpc-types' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-type-coverage/lib/rpc-types' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/pkg/nuclide-type-hint/lib/rpc-types' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/Symbol' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/TextDocument' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/TextDocuments' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/types' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/utils/connectionFromOptions' {
  declare module.exports: any;
}

declare module 'flow-language-server/lib/utils/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-language-server/dirs.js' {
  declare module.exports: $Exports<'flow-language-server/dirs'>;
}
declare module 'flow-language-server/lib/__tests__/ConnectionMock.js' {
  declare module.exports: $Exports<'flow-language-server/lib/__tests__/ConnectionMock'>;
}
declare module 'flow-language-server/lib/__tests__/TextDocuments.test.js' {
  declare module.exports: $Exports<'flow-language-server/lib/__tests__/TextDocuments.test'>;
}
declare module 'flow-language-server/lib/bin/cli.js' {
  declare module.exports: $Exports<'flow-language-server/lib/bin/cli'>;
}
declare module 'flow-language-server/lib/Completion.js' {
  declare module.exports: $Exports<'flow-language-server/lib/Completion'>;
}
declare module 'flow-language-server/lib/Definition.js' {
  declare module.exports: $Exports<'flow-language-server/lib/Definition'>;
}
declare module 'flow-language-server/lib/Diagnostics.js' {
  declare module.exports: $Exports<'flow-language-server/lib/Diagnostics'>;
}
declare module 'flow-language-server/lib/flow-versions/__tests__/flowBinForRoot.test.js' {
  declare module.exports: $Exports<'flow-language-server/lib/flow-versions/__tests__/flowBinForRoot.test'>;
}
declare module 'flow-language-server/lib/flow-versions/constants.js' {
  declare module.exports: $Exports<'flow-language-server/lib/flow-versions/constants'>;
}
declare module 'flow-language-server/lib/flow-versions/flowBinForRoot.js' {
  declare module.exports: $Exports<'flow-language-server/lib/flow-versions/flowBinForRoot'>;
}
declare module 'flow-language-server/lib/flow-versions/githubSemverDownloader.js' {
  declare module.exports: $Exports<'flow-language-server/lib/flow-versions/githubSemverDownloader'>;
}
declare module 'flow-language-server/lib/flow-versions/types.js' {
  declare module.exports: $Exports<'flow-language-server/lib/flow-versions/types'>;
}
declare module 'flow-language-server/lib/flow-versions/utils.js' {
  declare module.exports: $Exports<'flow-language-server/lib/flow-versions/utils'>;
}
declare module 'flow-language-server/lib/Hover.js' {
  declare module.exports: $Exports<'flow-language-server/lib/Hover'>;
}
declare module 'flow-language-server/lib/index.js' {
  declare module.exports: $Exports<'flow-language-server/lib/index'>;
}
declare module 'flow-language-server/lib/logging/connectionConsoleAppender.js' {
  declare module.exports: $Exports<'flow-language-server/lib/logging/connectionConsoleAppender'>;
}
declare module 'flow-language-server/lib/logging/fileAppender.js' {
  declare module.exports: $Exports<'flow-language-server/lib/logging/fileAppender'>;
}
declare module 'flow-language-server/lib/logging/initializeLogging.js' {
  declare module.exports: $Exports<'flow-language-server/lib/logging/initializeLogging'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-analytics.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-analytics'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-debugger-interfaces/rpc-types.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-debugger-interfaces/rpc-types'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-common/lib/main.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-common/lib/main'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/astToOutline.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/astToOutline'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/config.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/config'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/diagnosticsParser.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/diagnosticsParser'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowConstants.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowConstants'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowExecInfoContainer.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowExecInfoContainer'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowHelpers.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowHelpers'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowIDEConnection.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowIDEConnection'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowIDEConnectionWatcher.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowIDEConnectionWatcher'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/flowOutputTypes.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/flowOutputTypes'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowProcess.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowProcess'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowService.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowService'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowServiceState.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowServiceState'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowSingleProjectLanguageService.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowSingleProjectLanguageService'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowVersion.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/FlowVersion'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/prettyPrintTypes.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-flow-rpc/lib/prettyPrintTypes'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/HostServicesAggregator.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/HostServicesAggregator'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/main.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/main'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/MultiProjectLanguageService.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/MultiProjectLanguageService'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/NullLanguageService.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/NullLanguageService'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/rpc-types.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/rpc-types'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/ServerLanguageService.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-language-service-rpc/lib/ServerLanguageService'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-language-service/lib/LanguageService.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-language-service/lib/LanguageService'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/ConfigObserver.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/ConfigObserver'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/constants.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/constants'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/FileCache.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/FileCache'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/FileVersionNotifier.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/FileVersionNotifier'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/main.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/main'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/OpenFilesService.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/OpenFilesService'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/rpc-types.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-open-files-rpc/lib/rpc-types'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-type-coverage/lib/rpc-types.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-type-coverage/lib/rpc-types'>;
}
declare module 'flow-language-server/lib/pkg/nuclide-type-hint/lib/rpc-types.js' {
  declare module.exports: $Exports<'flow-language-server/lib/pkg/nuclide-type-hint/lib/rpc-types'>;
}
declare module 'flow-language-server/lib/Symbol.js' {
  declare module.exports: $Exports<'flow-language-server/lib/Symbol'>;
}
declare module 'flow-language-server/lib/TextDocument.js' {
  declare module.exports: $Exports<'flow-language-server/lib/TextDocument'>;
}
declare module 'flow-language-server/lib/TextDocuments.js' {
  declare module.exports: $Exports<'flow-language-server/lib/TextDocuments'>;
}
declare module 'flow-language-server/lib/types.js' {
  declare module.exports: $Exports<'flow-language-server/lib/types'>;
}
declare module 'flow-language-server/lib/utils/connectionFromOptions.js' {
  declare module.exports: $Exports<'flow-language-server/lib/utils/connectionFromOptions'>;
}
declare module 'flow-language-server/lib/utils/util.js' {
  declare module.exports: $Exports<'flow-language-server/lib/utils/util'>;
}
