// flow-typed signature: f95ec4b327ca73ff797e25a2c067b3fa
// flow-typed version: <<STUB>>/jest_v19.0.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest/bin/jest' {
  declare module.exports: any;
}

declare module 'jest/build/jest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest/bin/jest.js' {
  declare module.exports: $Exports<'jest/bin/jest'>;
}
declare module 'jest/build/jest.js' {
  declare module.exports: $Exports<'jest/build/jest'>;
}
