// flow-typed signature: 7196c8048f98e57ff14aa78b845b16c1
// flow-typed version: <<STUB>>/nightwatch-html-reporter_v^2.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nightwatch-html-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nightwatch-html-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nightwatch-html-reporter/lib/cli' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/lib/logger' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/lib/models/testRun' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/lib/normalize' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/lib/outputFilename' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/lib/relativePath' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/lib/renderer' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/lib/reporter' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/lib/themes/default/script' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/test/mockdata/nightwatchReport_0-6-4' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/test/mockdata/nightwatchReportObjects' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/test/mockdata/parsedxmlobjs_0-6-4' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/test/mockdata/parsedxmlobjs' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/test/normalize_test' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/test/outputFilename_test' {
  declare module.exports: any;
}

declare module 'nightwatch-html-reporter/test/renderer_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nightwatch-html-reporter/lib/cli.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/lib/cli'>;
}
declare module 'nightwatch-html-reporter/lib/logger.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/lib/logger'>;
}
declare module 'nightwatch-html-reporter/lib/models/testRun.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/lib/models/testRun'>;
}
declare module 'nightwatch-html-reporter/lib/normalize.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/lib/normalize'>;
}
declare module 'nightwatch-html-reporter/lib/outputFilename.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/lib/outputFilename'>;
}
declare module 'nightwatch-html-reporter/lib/relativePath.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/lib/relativePath'>;
}
declare module 'nightwatch-html-reporter/lib/renderer.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/lib/renderer'>;
}
declare module 'nightwatch-html-reporter/lib/reporter.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/lib/reporter'>;
}
declare module 'nightwatch-html-reporter/lib/themes/default/script.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/lib/themes/default/script'>;
}
declare module 'nightwatch-html-reporter/test/mockdata/nightwatchReport_0-6-4.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/test/mockdata/nightwatchReport_0-6-4'>;
}
declare module 'nightwatch-html-reporter/test/mockdata/nightwatchReportObjects.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/test/mockdata/nightwatchReportObjects'>;
}
declare module 'nightwatch-html-reporter/test/mockdata/parsedxmlobjs_0-6-4.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/test/mockdata/parsedxmlobjs_0-6-4'>;
}
declare module 'nightwatch-html-reporter/test/mockdata/parsedxmlobjs.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/test/mockdata/parsedxmlobjs'>;
}
declare module 'nightwatch-html-reporter/test/normalize_test.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/test/normalize_test'>;
}
declare module 'nightwatch-html-reporter/test/outputFilename_test.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/test/outputFilename_test'>;
}
declare module 'nightwatch-html-reporter/test/renderer_test.js' {
  declare module.exports: $Exports<'nightwatch-html-reporter/test/renderer_test'>;
}
