// flow-typed signature: 762068684cc58b14b765f08edaad6478
// flow-typed version: <<STUB>>/node-pty_v^0.7.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-pty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-pty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-pty/lib/index' {
  declare module.exports: any;
}

declare module 'node-pty/lib/interfaces' {
  declare module.exports: any;
}

declare module 'node-pty/lib/terminal' {
  declare module.exports: any;
}

declare module 'node-pty/lib/terminal.test' {
  declare module.exports: any;
}

declare module 'node-pty/lib/types' {
  declare module.exports: any;
}

declare module 'node-pty/lib/unixTerminal' {
  declare module.exports: any;
}

declare module 'node-pty/lib/unixTerminal.test' {
  declare module.exports: any;
}

declare module 'node-pty/lib/utils' {
  declare module.exports: any;
}

declare module 'node-pty/lib/windowsPtyAgent' {
  declare module.exports: any;
}

declare module 'node-pty/lib/windowsPtyAgent.test' {
  declare module.exports: any;
}

declare module 'node-pty/lib/windowsTerminal' {
  declare module.exports: any;
}

declare module 'node-pty/lib/windowsTerminal.test' {
  declare module.exports: any;
}

declare module 'node-pty/scripts/install' {
  declare module.exports: any;
}

declare module 'node-pty/scripts/post-install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-pty/lib/index.js' {
  declare module.exports: $Exports<'node-pty/lib/index'>;
}
declare module 'node-pty/lib/interfaces.js' {
  declare module.exports: $Exports<'node-pty/lib/interfaces'>;
}
declare module 'node-pty/lib/terminal.js' {
  declare module.exports: $Exports<'node-pty/lib/terminal'>;
}
declare module 'node-pty/lib/terminal.test.js' {
  declare module.exports: $Exports<'node-pty/lib/terminal.test'>;
}
declare module 'node-pty/lib/types.js' {
  declare module.exports: $Exports<'node-pty/lib/types'>;
}
declare module 'node-pty/lib/unixTerminal.js' {
  declare module.exports: $Exports<'node-pty/lib/unixTerminal'>;
}
declare module 'node-pty/lib/unixTerminal.test.js' {
  declare module.exports: $Exports<'node-pty/lib/unixTerminal.test'>;
}
declare module 'node-pty/lib/utils.js' {
  declare module.exports: $Exports<'node-pty/lib/utils'>;
}
declare module 'node-pty/lib/windowsPtyAgent.js' {
  declare module.exports: $Exports<'node-pty/lib/windowsPtyAgent'>;
}
declare module 'node-pty/lib/windowsPtyAgent.test.js' {
  declare module.exports: $Exports<'node-pty/lib/windowsPtyAgent.test'>;
}
declare module 'node-pty/lib/windowsTerminal.js' {
  declare module.exports: $Exports<'node-pty/lib/windowsTerminal'>;
}
declare module 'node-pty/lib/windowsTerminal.test.js' {
  declare module.exports: $Exports<'node-pty/lib/windowsTerminal.test'>;
}
declare module 'node-pty/scripts/install.js' {
  declare module.exports: $Exports<'node-pty/scripts/install'>;
}
declare module 'node-pty/scripts/post-install.js' {
  declare module.exports: $Exports<'node-pty/scripts/post-install'>;
}
