// flow-typed signature: af885e1640ed77bd360166f578e88cae
// flow-typed version: <<STUB>>/react-forms-state_valanzanattadev/react-forms-state/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-forms-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-forms-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-forms-state/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/jest-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/rxjs_v5.0.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/Form' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/Form.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormElement' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormEvents' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormModel' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormModel.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormWatcher' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormWatcher.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/index' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StateDispatcher' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StateDispatcher.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StatePathHelpers' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StateValueHelpers' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/ValidationComposition' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/ValidationComposition.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/ValidationHelpers' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/ValidationHelpers.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-forms-state/dist/bundle.js' {
  declare module.exports: $Exports<'react-forms-state/dist/bundle'>;
}
declare module 'react-forms-state/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'react-forms-state/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'react-forms-state/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'react-forms-state/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'react-forms-state/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'react-forms-state/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module 'react-forms-state/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'react-forms-state/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/jest_v20.x.x'>;
}
declare module 'react-forms-state/flow-typed/npm/jest-cli_vx.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/jest-cli_vx.x.x'>;
}
declare module 'react-forms-state/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'react-forms-state/flow-typed/npm/rxjs_v5.0.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/rxjs_v5.0.x'>;
}
declare module 'react-forms-state/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'react-forms-state/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'react-forms-state/lib/Form.js' {
  declare module.exports: $Exports<'react-forms-state/lib/Form'>;
}
declare module 'react-forms-state/lib/Form.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/Form.test'>;
}
declare module 'react-forms-state/lib/FormElement.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormElement'>;
}
declare module 'react-forms-state/lib/FormEvents.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormEvents'>;
}
declare module 'react-forms-state/lib/FormModel.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormModel'>;
}
declare module 'react-forms-state/lib/FormModel.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormModel.test'>;
}
declare module 'react-forms-state/lib/FormWatcher.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormWatcher'>;
}
declare module 'react-forms-state/lib/FormWatcher.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormWatcher.test'>;
}
declare module 'react-forms-state/lib/index.js' {
  declare module.exports: $Exports<'react-forms-state/lib/index'>;
}
declare module 'react-forms-state/lib/StateDispatcher.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StateDispatcher'>;
}
declare module 'react-forms-state/lib/StateDispatcher.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StateDispatcher.test'>;
}
declare module 'react-forms-state/lib/StatePathHelpers.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StatePathHelpers'>;
}
declare module 'react-forms-state/lib/StateValueHelpers.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StateValueHelpers'>;
}
declare module 'react-forms-state/lib/ValidationComposition.js' {
  declare module.exports: $Exports<'react-forms-state/lib/ValidationComposition'>;
}
declare module 'react-forms-state/lib/ValidationComposition.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/ValidationComposition.test'>;
}
declare module 'react-forms-state/lib/ValidationHelpers.js' {
  declare module.exports: $Exports<'react-forms-state/lib/ValidationHelpers'>;
}
declare module 'react-forms-state/lib/ValidationHelpers.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/ValidationHelpers.test'>;
}
declare module 'react-forms-state/webpack.config.js' {
  declare module.exports: $Exports<'react-forms-state/webpack.config'>;
}
