// flow-typed signature: 5eff41dbc5e8008d241c51ac56d8c483
// flow-typed version: <<STUB>>/react-image-fallback_v^3.3.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-fallback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-fallback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-fallback/lib/index' {
  declare module.exports: any;
}

declare module 'react-image-fallback/lib/lib/filter-dom-props' {
  declare module.exports: any;
}

declare module 'react-image-fallback/lib/native' {
  declare module.exports: any;
}

declare module 'react-image-fallback/lib/shared' {
  declare module.exports: any;
}

declare module 'react-image-fallback/src/index' {
  declare module.exports: any;
}

declare module 'react-image-fallback/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-fallback/lib/index.js' {
  declare module.exports: $Exports<'react-image-fallback/lib/index'>;
}
declare module 'react-image-fallback/lib/lib/filter-dom-props.js' {
  declare module.exports: $Exports<'react-image-fallback/lib/lib/filter-dom-props'>;
}
declare module 'react-image-fallback/lib/native.js' {
  declare module.exports: $Exports<'react-image-fallback/lib/native'>;
}
declare module 'react-image-fallback/lib/shared.js' {
  declare module.exports: $Exports<'react-image-fallback/lib/shared'>;
}
declare module 'react-image-fallback/src/index.js' {
  declare module.exports: $Exports<'react-image-fallback/src/index'>;
}
declare module 'react-image-fallback/test/index.js' {
  declare module.exports: $Exports<'react-image-fallback/test/index'>;
}
