// flow-typed signature: 7dba72ee5b82ce7c026fd852352cb9fe
// flow-typed version: <<STUB>>/react-forms-state_valanzanattadev/react-forms-state/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-forms-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-forms-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-forms-state/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormController' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormController.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormEvents' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormModel' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/FormModel.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/index' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StateDispatcher' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StateDispatcher.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StateInjector' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StateInjector.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StatePathHelpers' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StateProxy' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/StateValueHelpers' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/ValidationComposition' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/ValidationComposition.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/ValidationHelpers' {
  declare module.exports: any;
}

declare module 'react-forms-state/lib/ValidationHelpers.test' {
  declare module.exports: any;
}

declare module 'react-forms-state/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-forms-state/dist/bundle.js' {
  declare module.exports: $Exports<'react-forms-state/dist/bundle'>;
}
declare module 'react-forms-state/lib/FormController.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormController'>;
}
declare module 'react-forms-state/lib/FormController.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormController.test'>;
}
declare module 'react-forms-state/lib/FormEvents.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormEvents'>;
}
declare module 'react-forms-state/lib/FormModel.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormModel'>;
}
declare module 'react-forms-state/lib/FormModel.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/FormModel.test'>;
}
declare module 'react-forms-state/lib/index.js' {
  declare module.exports: $Exports<'react-forms-state/lib/index'>;
}
declare module 'react-forms-state/lib/StateDispatcher.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StateDispatcher'>;
}
declare module 'react-forms-state/lib/StateDispatcher.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StateDispatcher.test'>;
}
declare module 'react-forms-state/lib/StateInjector.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StateInjector'>;
}
declare module 'react-forms-state/lib/StateInjector.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StateInjector.test'>;
}
declare module 'react-forms-state/lib/StatePathHelpers.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StatePathHelpers'>;
}
declare module 'react-forms-state/lib/StateProxy.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StateProxy'>;
}
declare module 'react-forms-state/lib/StateValueHelpers.js' {
  declare module.exports: $Exports<'react-forms-state/lib/StateValueHelpers'>;
}
declare module 'react-forms-state/lib/ValidationComposition.js' {
  declare module.exports: $Exports<'react-forms-state/lib/ValidationComposition'>;
}
declare module 'react-forms-state/lib/ValidationComposition.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/ValidationComposition.test'>;
}
declare module 'react-forms-state/lib/ValidationHelpers.js' {
  declare module.exports: $Exports<'react-forms-state/lib/ValidationHelpers'>;
}
declare module 'react-forms-state/lib/ValidationHelpers.test.js' {
  declare module.exports: $Exports<'react-forms-state/lib/ValidationHelpers.test'>;
}
declare module 'react-forms-state/webpack.config.js' {
  declare module.exports: $Exports<'react-forms-state/webpack.config'>;
}
