// flow-typed signature: d64e7add16a0d3e7e9edf43b2379b870
// flow-typed version: <<STUB>>/stream-buffers_v^3.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-buffers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-buffers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-buffers/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'stream-buffers/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'stream-buffers/lib/constants' {
  declare module.exports: any;
}

declare module 'stream-buffers/lib/readable_streambuffer' {
  declare module.exports: any;
}

declare module 'stream-buffers/lib/streambuffer' {
  declare module.exports: any;
}

declare module 'stream-buffers/lib/writable_streambuffer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-buffers/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'stream-buffers/coverage/lcov-report/prettify'>;
}
declare module 'stream-buffers/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'stream-buffers/coverage/lcov-report/sorter'>;
}
declare module 'stream-buffers/lib/constants.js' {
  declare module.exports: $Exports<'stream-buffers/lib/constants'>;
}
declare module 'stream-buffers/lib/readable_streambuffer.js' {
  declare module.exports: $Exports<'stream-buffers/lib/readable_streambuffer'>;
}
declare module 'stream-buffers/lib/streambuffer.js' {
  declare module.exports: $Exports<'stream-buffers/lib/streambuffer'>;
}
declare module 'stream-buffers/lib/writable_streambuffer.js' {
  declare module.exports: $Exports<'stream-buffers/lib/writable_streambuffer'>;
}
