// flow-typed signature: ab446a1e92f2dd3e3f19936aa565d648
// flow-typed version: <<STUB>>/vscode-jsonrpc_v^3.5.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-jsonrpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-jsonrpc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-jsonrpc/lib/cancellation' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/events' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/is' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/linkedMap' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/main' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/messageReader' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/messages' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/messageWriter' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/pipeSupport' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/socketSupport' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/thenable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-jsonrpc/lib/cancellation.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/cancellation'>;
}
declare module 'vscode-jsonrpc/lib/events.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/events'>;
}
declare module 'vscode-jsonrpc/lib/is.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/is'>;
}
declare module 'vscode-jsonrpc/lib/linkedMap.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/linkedMap'>;
}
declare module 'vscode-jsonrpc/lib/main.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/main'>;
}
declare module 'vscode-jsonrpc/lib/messageReader.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/messageReader'>;
}
declare module 'vscode-jsonrpc/lib/messages.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/messages'>;
}
declare module 'vscode-jsonrpc/lib/messageWriter.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/messageWriter'>;
}
declare module 'vscode-jsonrpc/lib/pipeSupport.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/pipeSupport'>;
}
declare module 'vscode-jsonrpc/lib/socketSupport.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/socketSupport'>;
}
declare module 'vscode-jsonrpc/lib/thenable.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/thenable'>;
}
