// flow-typed signature: 9102f3806ec36faf52f8e63b2ad79bef
// flow-typed version: <<STUB>>/xterm_v^2.5.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xterm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xterm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xterm/dist/addons/attach/attach' {
  declare module.exports: any;
}

declare module 'xterm/dist/addons/fit/fit' {
  declare module.exports: any;
}

declare module 'xterm/dist/addons/fullscreen/fullscreen' {
  declare module.exports: any;
}

declare module 'xterm/dist/addons/linkify/linkify' {
  declare module.exports: any;
}

declare module 'xterm/dist/addons/terminado/terminado' {
  declare module.exports: any;
}

declare module 'xterm/dist/xterm' {
  declare module.exports: any;
}

declare module 'xterm/gulpfile' {
  declare module.exports: any;
}

declare module 'xterm/lib/addons/attach/attach' {
  declare module.exports: any;
}

declare module 'xterm/lib/addons/fit/fit' {
  declare module.exports: any;
}

declare module 'xterm/lib/addons/fullscreen/fullscreen' {
  declare module.exports: any;
}

declare module 'xterm/lib/addons/terminado/terminado' {
  declare module.exports: any;
}

declare module 'xterm/lib/Charsets' {
  declare module.exports: any;
}

declare module 'xterm/lib/CompositionHelper' {
  declare module.exports: any;
}

declare module 'xterm/lib/CompositionHelper.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/EscapeSequences' {
  declare module.exports: any;
}

declare module 'xterm/lib/EventEmitter' {
  declare module.exports: any;
}

declare module 'xterm/lib/EventEmitter.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/handlers/Clipboard' {
  declare module.exports: any;
}

declare module 'xterm/lib/handlers/Clipboard.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/InputHandler' {
  declare module.exports: any;
}

declare module 'xterm/lib/InputHandler.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/Interfaces' {
  declare module.exports: any;
}

declare module 'xterm/lib/Linkifier' {
  declare module.exports: any;
}

declare module 'xterm/lib/Linkifier.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/Parser' {
  declare module.exports: any;
}

declare module 'xterm/lib/Renderer' {
  declare module.exports: any;
}

declare module 'xterm/lib/SelectionManager' {
  declare module.exports: any;
}

declare module 'xterm/lib/SelectionManager.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/SelectionModel' {
  declare module.exports: any;
}

declare module 'xterm/lib/SelectionModel.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/test/addons/test' {
  declare module.exports: any;
}

declare module 'xterm/lib/test/escape-sequences-test' {
  declare module.exports: any;
}

declare module 'xterm/lib/test/test' {
  declare module.exports: any;
}

declare module 'xterm/lib/Types' {
  declare module.exports: any;
}

declare module 'xterm/lib/utils/Browser' {
  declare module.exports: any;
}

declare module 'xterm/lib/utils/CharMeasure' {
  declare module.exports: any;
}

declare module 'xterm/lib/utils/CharMeasure.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/utils/CircularList' {
  declare module.exports: any;
}

declare module 'xterm/lib/utils/CircularList.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/utils/DomElementObjectPool' {
  declare module.exports: any;
}

declare module 'xterm/lib/utils/DomElementObjectPool.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/utils/Generic' {
  declare module.exports: any;
}

declare module 'xterm/lib/utils/Mouse' {
  declare module.exports: any;
}

declare module 'xterm/lib/Viewport' {
  declare module.exports: any;
}

declare module 'xterm/lib/Viewport.test' {
  declare module.exports: any;
}

declare module 'xterm/lib/xterm' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/attach/attach' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/fit/fit' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/fullscreen/fullscreen' {
  declare module.exports: any;
}

declare module 'xterm/src/addons/terminado/terminado' {
  declare module.exports: any;
}

declare module 'xterm/src/test/addons/test' {
  declare module.exports: any;
}

declare module 'xterm/src/test/escape-sequences-test' {
  declare module.exports: any;
}

declare module 'xterm/src/test/test' {
  declare module.exports: any;
}

declare module 'xterm/src/xterm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xterm/dist/addons/attach/attach.js' {
  declare module.exports: $Exports<'xterm/dist/addons/attach/attach'>;
}
declare module 'xterm/dist/addons/fit/fit.js' {
  declare module.exports: $Exports<'xterm/dist/addons/fit/fit'>;
}
declare module 'xterm/dist/addons/fullscreen/fullscreen.js' {
  declare module.exports: $Exports<'xterm/dist/addons/fullscreen/fullscreen'>;
}
declare module 'xterm/dist/addons/linkify/linkify.js' {
  declare module.exports: $Exports<'xterm/dist/addons/linkify/linkify'>;
}
declare module 'xterm/dist/addons/terminado/terminado.js' {
  declare module.exports: $Exports<'xterm/dist/addons/terminado/terminado'>;
}
declare module 'xterm/dist/xterm.js' {
  declare module.exports: $Exports<'xterm/dist/xterm'>;
}
declare module 'xterm/gulpfile.js' {
  declare module.exports: $Exports<'xterm/gulpfile'>;
}
declare module 'xterm/lib/addons/attach/attach.js' {
  declare module.exports: $Exports<'xterm/lib/addons/attach/attach'>;
}
declare module 'xterm/lib/addons/fit/fit.js' {
  declare module.exports: $Exports<'xterm/lib/addons/fit/fit'>;
}
declare module 'xterm/lib/addons/fullscreen/fullscreen.js' {
  declare module.exports: $Exports<'xterm/lib/addons/fullscreen/fullscreen'>;
}
declare module 'xterm/lib/addons/terminado/terminado.js' {
  declare module.exports: $Exports<'xterm/lib/addons/terminado/terminado'>;
}
declare module 'xterm/lib/Charsets.js' {
  declare module.exports: $Exports<'xterm/lib/Charsets'>;
}
declare module 'xterm/lib/CompositionHelper.js' {
  declare module.exports: $Exports<'xterm/lib/CompositionHelper'>;
}
declare module 'xterm/lib/CompositionHelper.test.js' {
  declare module.exports: $Exports<'xterm/lib/CompositionHelper.test'>;
}
declare module 'xterm/lib/EscapeSequences.js' {
  declare module.exports: $Exports<'xterm/lib/EscapeSequences'>;
}
declare module 'xterm/lib/EventEmitter.js' {
  declare module.exports: $Exports<'xterm/lib/EventEmitter'>;
}
declare module 'xterm/lib/EventEmitter.test.js' {
  declare module.exports: $Exports<'xterm/lib/EventEmitter.test'>;
}
declare module 'xterm/lib/handlers/Clipboard.js' {
  declare module.exports: $Exports<'xterm/lib/handlers/Clipboard'>;
}
declare module 'xterm/lib/handlers/Clipboard.test.js' {
  declare module.exports: $Exports<'xterm/lib/handlers/Clipboard.test'>;
}
declare module 'xterm/lib/InputHandler.js' {
  declare module.exports: $Exports<'xterm/lib/InputHandler'>;
}
declare module 'xterm/lib/InputHandler.test.js' {
  declare module.exports: $Exports<'xterm/lib/InputHandler.test'>;
}
declare module 'xterm/lib/Interfaces.js' {
  declare module.exports: $Exports<'xterm/lib/Interfaces'>;
}
declare module 'xterm/lib/Linkifier.js' {
  declare module.exports: $Exports<'xterm/lib/Linkifier'>;
}
declare module 'xterm/lib/Linkifier.test.js' {
  declare module.exports: $Exports<'xterm/lib/Linkifier.test'>;
}
declare module 'xterm/lib/Parser.js' {
  declare module.exports: $Exports<'xterm/lib/Parser'>;
}
declare module 'xterm/lib/Renderer.js' {
  declare module.exports: $Exports<'xterm/lib/Renderer'>;
}
declare module 'xterm/lib/SelectionManager.js' {
  declare module.exports: $Exports<'xterm/lib/SelectionManager'>;
}
declare module 'xterm/lib/SelectionManager.test.js' {
  declare module.exports: $Exports<'xterm/lib/SelectionManager.test'>;
}
declare module 'xterm/lib/SelectionModel.js' {
  declare module.exports: $Exports<'xterm/lib/SelectionModel'>;
}
declare module 'xterm/lib/SelectionModel.test.js' {
  declare module.exports: $Exports<'xterm/lib/SelectionModel.test'>;
}
declare module 'xterm/lib/test/addons/test.js' {
  declare module.exports: $Exports<'xterm/lib/test/addons/test'>;
}
declare module 'xterm/lib/test/escape-sequences-test.js' {
  declare module.exports: $Exports<'xterm/lib/test/escape-sequences-test'>;
}
declare module 'xterm/lib/test/test.js' {
  declare module.exports: $Exports<'xterm/lib/test/test'>;
}
declare module 'xterm/lib/Types.js' {
  declare module.exports: $Exports<'xterm/lib/Types'>;
}
declare module 'xterm/lib/utils/Browser.js' {
  declare module.exports: $Exports<'xterm/lib/utils/Browser'>;
}
declare module 'xterm/lib/utils/CharMeasure.js' {
  declare module.exports: $Exports<'xterm/lib/utils/CharMeasure'>;
}
declare module 'xterm/lib/utils/CharMeasure.test.js' {
  declare module.exports: $Exports<'xterm/lib/utils/CharMeasure.test'>;
}
declare module 'xterm/lib/utils/CircularList.js' {
  declare module.exports: $Exports<'xterm/lib/utils/CircularList'>;
}
declare module 'xterm/lib/utils/CircularList.test.js' {
  declare module.exports: $Exports<'xterm/lib/utils/CircularList.test'>;
}
declare module 'xterm/lib/utils/DomElementObjectPool.js' {
  declare module.exports: $Exports<'xterm/lib/utils/DomElementObjectPool'>;
}
declare module 'xterm/lib/utils/DomElementObjectPool.test.js' {
  declare module.exports: $Exports<'xterm/lib/utils/DomElementObjectPool.test'>;
}
declare module 'xterm/lib/utils/Generic.js' {
  declare module.exports: $Exports<'xterm/lib/utils/Generic'>;
}
declare module 'xterm/lib/utils/Mouse.js' {
  declare module.exports: $Exports<'xterm/lib/utils/Mouse'>;
}
declare module 'xterm/lib/Viewport.js' {
  declare module.exports: $Exports<'xterm/lib/Viewport'>;
}
declare module 'xterm/lib/Viewport.test.js' {
  declare module.exports: $Exports<'xterm/lib/Viewport.test'>;
}
declare module 'xterm/lib/xterm.js' {
  declare module.exports: $Exports<'xterm/lib/xterm'>;
}
declare module 'xterm/src/addons/attach/attach.js' {
  declare module.exports: $Exports<'xterm/src/addons/attach/attach'>;
}
declare module 'xterm/src/addons/fit/fit.js' {
  declare module.exports: $Exports<'xterm/src/addons/fit/fit'>;
}
declare module 'xterm/src/addons/fullscreen/fullscreen.js' {
  declare module.exports: $Exports<'xterm/src/addons/fullscreen/fullscreen'>;
}
declare module 'xterm/src/addons/terminado/terminado.js' {
  declare module.exports: $Exports<'xterm/src/addons/terminado/terminado'>;
}
declare module 'xterm/src/test/addons/test.js' {
  declare module.exports: $Exports<'xterm/src/test/addons/test'>;
}
declare module 'xterm/src/test/escape-sequences-test.js' {
  declare module.exports: $Exports<'xterm/src/test/escape-sequences-test'>;
}
declare module 'xterm/src/test/test.js' {
  declare module.exports: $Exports<'xterm/src/test/test'>;
}
declare module 'xterm/src/xterm.js' {
  declare module.exports: $Exports<'xterm/src/xterm'>;
}
